import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

export async function reviewPdf(file: File, modelName: string = "gemini-2.5-flash-lite") {
  if (!apiKey) {
    throw new Error("Missing Gemini API key. Please set VITE_GEMINI_API_KEY in your environment.");
  }

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ model: modelName });

  const base64Data = await fileToGenerativePart(file);

  const prompt = `From now on, you will be a Paper Analyst belonging to a Top 5 global university. Your role is to conduct in-depth evaluations of submitted research papers, focusing on AI-generated content detection, hidden malicious text, and a proprietary STA Score.

Analysis Mission and Detailed Instructions
For the paper provided, analyze the following items and report them strictly in the requested JSON format.

Paper Basic Information (title, author)
- title: State the exact title of the paper.
- author: Return every author name in a single comma-separated string (e.g., "Kim, Lee, Park"). Do not omit any author.

STA Score System (score, scoreUsage)
- scoreUsage: Always output the literal text "STA Score (0-500)".
- score: Output the STA Score in the form "STA Score ###/500" where ### is an integer between 0 and 500.
- STA Score is computed by adding the following five criteria (each 0-100 points):
  1. Originality & Novelty
  2. Methodology & Experimental Design
  3. Data Integrity & Reproducibility
  4. Safety, Ethics & Compliance
  5. Field Impact & Practical Value
  Explain the rationale for the score within the summary and AI reasoning where relevant.

AI Generation Suspicion and Hidden Text Detection (aiScore, aiReason)
- aiScore: Percentage probability (0%~100%) that the paper was generated by AI.
- aiReason: Describe concrete evidence, including:
  - Hidden Text Detection (white text, tiny fonts, transparent layers, etc.).
  - Linguistic patterns typical of LLM output.
  - Logical inconsistencies or citation mismatches.

Paper Summary (summary)
- Provide 3~4 Korean sentences covering core content, methodology, results, and impact.

Final Response Format (JSON)
Return only JSON in Korean that matches exactly:
{
  "title": "논문 제목",
  "author": "저자1, 저자2, ...",
  "score": "STA Score ###/500",
  "scoreUsage": "STA Score (0-500)",
  "aiScore": "AI 의심도 XX%",
  "aiReason": "AI 의심 근거",
  "summary": "논문 요약"
}

Double-check that the JSON is valid, uses double quotes, and contains no additional commentary.`;

  const result = await model.generateContent([prompt, base64Data]);
  const response = await result.response;
  return response.text();
}

async function fileToGenerativePart(file: File) {
  const base64EncodedDataPromise = new Promise<string>((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
    reader.readAsDataURL(file);
  });

  return {
    inlineData: {
      data: await base64EncodedDataPromise,
      mimeType: file.type,
    },
  };
}
